// Runtime overlay that injects per-destination prose overviews from
// src/data/prose-overview.json into each Destination without modifying
// the underlying destinations-*.ts data files.
//
// The JSON is generated by scripts/generate-prose.ts and committed to
// the repo. Cities without prose entries render unchanged.

import type { Destination } from "./types";
import proseStore from "./prose-overview.json";

interface ProseEntry {
  prose: string;
  generatedAt: string;
  model: string;
}

const STORE = proseStore as Record<string, ProseEntry>;

export function applyProseOverlay(destinations: Destination[]): Destination[] {
  return destinations.map((d) => {
    const entry = STORE[d.id];
    if (!entry) return d;
    return { ...d, proseOverview: entry.prose };
  });
}
